### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by EmbeddedAndroid** [stacks-archive/sbtc-bridge-api#82] opened 2023-10-02 13:57 UTC
The sBTC team has received a report the bridge-api is no longer building in devenv: https://github.com/stacks-network/sbtc/issues/210#issuecomment-1743045478

```
 => ERROR [sbtc-bridge-api  9/10] RUN npm run build                                     4.3s
------
 > [sbtc-bridge-api  9/10] RUN npm run build:
0.720
0.720 > bridge-api@1.0.0 prebuild
0.720 > npm run swagger
0.720
1.022
1.022 > bridge-api@1.0.0 swagger
1.022 > tsoa spec
1.022
2.413
2.413 > bridge-api@1.0.0 build
2.413 > tsc
2.413
4.285 src/routes/bitcoin/BitcoinRPCController.ts(56,67): error TS2339: Property 'btcSchnorrReveal' does not exist on type '{ mongoDbUrl: string; mongoUser: string; mongoPwd: string; mongoDbName: string; btcNode: string; btcRpcUser: string; btcRpcPwd: string; host: string; port: number; walletPath: string; network: string; ... 7 more ...; publicAppVersion: string; }'.
4.285 src/routes/bitcoin/BitcoinRPCController.ts(57,68): error TS2339: Property 'btcSchnorrReclaim' does not exist on type '{ mongoDbUrl: string; mongoUser: string; mongoPwd: string; mongoDbName: string; btcNode: string; btcRpcUser: string; btcRpcPwd: string; host: string; port: number; walletPath: string; network: string; ... 7 more ...; publicAppVersion: string; }'.
4.285 src/routes/bitcoin/BitcoinRPCController.ts(153,49): error TS2339: Property 'btcSchnorrReclaim' does not exist on type '{ mongoDbUrl: string; mongoUser: string; mongoPwd: string; mongoDbName: string; btcNode: string; btcRpcUser: string; btcRpcPwd: string; host: string; port: number; walletPath: string; network: string; ... 7 more ...; publicAppVersion: string; }'.
4.285 src/routes/bitcoin/BitcoinRPCController.ts(155,49): error TS2339: Property 'btcSchnorrReveal' does not exist on type '{ mongoDbUrl: string; mongoUser: string; mongoPwd: string; mongoDbName: string; btcNode: string; btcRpcUser: string; btcRpcPwd: string; host: string; port: number; walletPath: string; network: string; ... 7 more ...; publicAppVersion: string; }'.
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 2
```

I've bisected the build error to this commit: https://github.com/stacks-network/sbtc-bridge-api/commit/44ccfe1f9f171e31e01c8fd706874c8c824ea7d2

**Comment by radicleart** [comment] 2023-10-02 16:17
I've been looking into this but failed to find the cause. The issue is fixed in main in https://github.com/stacks-network/sbtc-bridge-api.

In devenv I found the error remained until I switched to using --no-cache and then it builds with this config in the docker file

```
ARG BRIDGE_GIT_URI='https://github.com/stacks-network/sbtc-bridge-api.git'
ARG BRIDGE_GIT_BRANCH='main'
...
RUN git clone ${BRIDGE_GIT_URI} .
RUN git checkout ${BRIDGE_GIT_BRANCH}
```

it builds successfully..


``` => CACHED [ 7/10] RUN npm install                                                                                                                                                                         0.0s
 => CACHED [ 8/10] RUN npm run swagger                                                                                                                                                                     0.0s
 => CACHED [ 9/10] RUN npm run build                                                                                                                                                                       0.0s
 => CACHED [10/10] RUN cp src/swagger.json dist/src/                                                                                                                                                       0.0s
 => exporting to image                                                                                                                                                                                     0.0s
 => => exporting layers                                                                                                                                                                                    0.0s
 => => writing image sha256:ebb6efa6a9236af3103b83f54f501766467777deabf90276bb9d599938930331                                                                                                               0.0s
 => => naming to docker.io/library/sbtc-bridge-api:latest                                                                                                                                                  0.0s```

**Closed as completed** 2023-10-02 16:41 UTC
